---

- hosts: all
  become: true
  gather_facts: no
  tasks:

  - name: install apache2 package
    yum:
      name: httpd

  - name: populate index.html file
    lineinfile:
      path: /var/www/html/index.html
      line: hello world this is my ansible webserver

  - name: start the httpd service
    service: 
      name: httpd
      state: restarted 
   
